id: CVE Enrichment - Generic v2
version: -1
fromversion: 5.0.0
name: CVE Enrichment - Generic v2
description: |-
  This playbook performs CVE Enrichment using one or more integrations.
  Supported integrations:
  - VulnDB
  - CIRCL CVE Search
  - IBM X-Force Exchange
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 8a9b5f57-93dc-4f6e-847a-472c93c1af17
    type: start
    task:
      id: 8a9b5f57-93dc-4f6e-847a-472c93c1af17
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 4cfa2898-da16-4d61-839a-cc66e5492541
    type: condition
    task:
      id: 4cfa2898-da16-4d61-839a-cc66e5492541
      version: -1
      name: Is there a CVE to enrich?
      description: Verify that the playbook input includes at least one CVE ID to enrich.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '11'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.cve_id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '2':
    id: '2'
    taskid: 1c1df4a5-6a12-4724-8cf5-586f7743fc57
    type: title
    task:
      id: 1c1df4a5-6a12-4724-8cf5-586f7743fc57
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '7':
    id: '7'
    taskid: 54844794-c82a-4e73-8cf6-52e5598dbc89
    type: regular
    task:
      id: 54844794-c82a-4e73-8cf6-52e5598dbc89
      version: -1
      name: Get vulnerability details by CVE
      description: Search for details about the given CVE.
      script: '|||cve-search'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      cve_id:
        complex:
          root: inputs.cve_id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 800,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 81a2e52a-0a2a-4791-8a55-e4249923b7b3
    type: title
    task:
      id: 81a2e52a-0a2a-4791-8a55-e4249923b7b3
      version: -1
      name: CVE enrichment
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - "12"
      - "7"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 600,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 38a9e31d-b066-4c7d-8a90-19d9b7f2e8d4
    type: regular
    task:
      id: 38a9e31d-b066-4c7d-8a90-19d9b7f2e8d4
      version: -1
      name: Get vulnerability details by CVE
      description: Returns CVE information by CVE ID.
      script: '|||cve'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      cve:
        complex:
          root: inputs.cve_id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 400,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerror: true
    continueonerrortype: ""
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "1_11_yes": 0.52,
      "1_2_#default#": 0.25
    },
    "paper": {
      "dimensions": {
        "height": 685,
        "width": 1017.5,
        "x": 162.5,
        "y": 200
      }
    }
  }
inputs:
- key: cve_id
  value:
    complex:
      root: CVE
      accessor: ID
  required: false
  description: The CVE ID to enrich.
  playbookInputQuery:
outputs:
- contextPath: CVE
  description: The CVE object
  type: string
- contextPath: CVE.ID
  description: The ID of the CVE
  type: string
- contextPath: CVE.CVSS
  description: The CVSS score of the CVE
  type: number
- contextPath: CVE.Published
  description: The date this was published
  type: date
- contextPath: CVE.Modified
  description: When CVE was last modified
  type: date
- contextPath: CVE.Description
  description: The CVE description
  type: string
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: string
- contextPath: DBotScore.Type
  description: The indicator type.
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: string
- contextPath: XFE.CVE.Xfdbid
  description: The XFBID of the CVE.
  type: string
- contextPath: XFE.CVE.RiskLevel
  description: The risk level of the CVE.
  type: string
- contextPath: XFE.CVE.Reported
  description: The reported date of the CVE.
  type: string
- contextPath: XFE.CVE.Cvss
  description: The CVSS information of the CVE.
  type: string
- contextPath: XFE.CVE.Stdcode
  description: The CVE stdcodes.
  type: string
- contextPath: XFE.CVE.Title
  description: The title of the CVE.
  type: string
- contextPath: XFE.CVE.Description
  description: The description of the CVE.
  type: string
- contextPath: XFE.CVE.PlatformsAffected
  description: The affetcted platforms due to the CVE.
  type: string
- contextPath: XFE.CVE.Exploitability
  description: The exploitability of the CVE.
  type: string
- contextPath: VulnDB.Vulnerability
  description: The Vulnerability object
  type: string
- contextPath: VulnDB.Vulnerability.ID
  description: Vulnerability ID.
  type: string
- contextPath: VulnDB.Vulnerability.Title
  description: Vulnerability title (human readable).
  type: string
- contextPath: VulnDB.Vulnerability.Keywords
  description: Vulnerability keywords.
  type: string
- contextPath: VulnDB.Vulnerability.Solution
  description: Vulnerability solution (human readable).
  type: string
- contextPath: VulnDB.Vulnerability.PublishedDate
  description: Vulnerability published date.
  type: date
- contextPath: VulnDB.Vulnerability.TDescription
  description: Vulnerability description (human readable).
  type: string
- contextPath: VulnDB.Vulnerability.SolutionDate
  description: Vulnerability solution date.
  type: date
- contextPath: VulnDB.Vulnerability.DiscoveryDate
  description: Vulnerability discovery date.
  type: date
- contextPath: VulnDB.Vulnerability.ExploitPublishDate
  description: Exploit publish date.
  type: date
- contextPath: VulnDB.CVE-ExtReferences
  description: The Vulnerability References Objects
  type: string
- contextPath: VulnDB.CVE-ExtReferences.Value
  description: CVE (constant string).
  type: string
- contextPath: VulnDB.CvssMetrics
  description: The Common Vulnerability Scoring Metrics
  type: string
- contextPath: VulnDB.CvssMetrics.Id
  description: CVSS reference value.
  type: string
- contextPath: VulnDB.CvssMetrics.AccessVector
  description: CVSS access vector.
  type: string
- contextPath: VulnDB.CvssMetrics.AccessComplexity
  description: CVSS access complexity.
  type: string
- contextPath: VulnDB.CvssMetrics.Authentication
  description: CVSS metric authentication.
  type: string
- contextPath: VulnDB.CvssMetrics.ConfidentialityImpact
  description: CVSS confidentiality impact.
  type: string
- contextPath: VulnDB.CvssMetrics.AvailabilityImpact
  description: CVSS availability impact.
  type: string
- contextPath: VulnDB.CvssMetrics.Generated_on
  description: CVSS metric date.
  type: date
- contextPath: VulnDB.CvssMetrics.Score
  description: CVSS score.
  type: string
- contextPath: VulnDB.cvssMetrics.integrity_impact
  description: CVSS integrity impact.
  type: string
- contextPath: VulnDB.Vendors
  description: Vendors Object
  type: string
- contextPath: VulnDB.Vendors.Id
  description: Vendor ID.
  type: string
- contextPath: VulnDB.Vendor
  description: Vendor Objects
  type: string
- contextPath: VulnDB.Vendor.Name
  description: Vendor name.
  type: string
- contextPath: VulnDB.Products
  description: Products Object
  type: string
- contextPath: VulnDB.Products.Id
  description: Product IDs.
  type: string
- contextPath: VulnDB.Products.Name
  description: Product names.
  type: string
- contextPath: VulnDB.Products.Versions
  description: Products version
  type: string
- contextPath: VulnDB.Products.Versions.Id
  description: Product version IDs.
  type: string
- contextPath: VulnDB.Products.Versions.Name
  description: Product version names.
  type: string
- contextPath: VulnDB.Classification
  description: Classification Object
  type: string
- contextPath: VulnDB.Classification.Longname
  description: Classification name (long).
  type: string
- contextPath: VulnDB.Classification.Description
  description: Classification description (human readable).
  type: string
tests:
- No test
marketplaces:
  - xsoar
  - marketplacev2
contentitemexportablefields:
  contentitemfields: {}
