id: CVE Enrichment - Generic v2
version: -1
fromversion: 5.0.0
name: CVE Enrichment - Generic v2
description: |-
  This playbook performs CVE Enrichment using the following integrations:
  - VulnDB
  - CIRCL CVE Search
  - IBM X-Force Exchange
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 8a9b5f57-93dc-4f6e-847a-472c93c1af17
    type: start
    task:
      id: 8a9b5f57-93dc-4f6e-847a-472c93c1af17
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 4cfa2898-da16-4d61-839a-cc66e5492541
    type: condition
    task:
      id: 4cfa2898-da16-4d61-839a-cc66e5492541
      version: -1
      name: Is there a CVE to enrich?
      description: Verify that the playbook input includes at least one CVE ID to enrich.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '11'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: inputs.cve_id
            iscontext: true
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 340
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '2':
    id: '2'
    taskid: 1c1df4a5-6a12-4724-8cf5-586f7743fc57
    type: title
    task:
      id: 1c1df4a5-6a12-4724-8cf5-586f7743fc57
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1130
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '4':
    id: '4'
    taskid: 5199c9bb-9a57-4d36-80fe-3bc1035e785e
    type: condition
    task:
      id: 5199c9bb-9a57-4d36-80fe-3bc1035e785e
      version: -1
      name: Is IBM X-Force Exchange integration enabled?
      description: Verify that there's a valid instance of "IBM X-Force Exchange" enabled.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '7'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: XFE_v2
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1530,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: e2170ae3-622d-45d9-882b-b1ee14f1e1b3
    type: condition
    task:
      id: e2170ae3-622d-45d9-882b-b1ee14f1e1b3
      version: -1
      name: Is CIRCL CVE Search integration enabled?
      description: Verify that there's a valid instance of "CIRCL CVE Search" enabled.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '6'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: CIRCL CVE Search
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          right:
            value: {}
    view: |-
      {
        "position": {
          "x": 970,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d967878f-480e-4e27-8eb0-a193826cd386
    type: regular
    task:
      id: d967878f-480e-4e27-8eb0-a193826cd386
      version: -1
      name: Get CVE info from CIRCL CVE Search
      description: Returns CVE information by CVE ID.
      script: 'CIRCL CVE Search|||cve'
      type: regular
      iscommand: true
      brand: CIRCL CVE Search
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      cve:
        complex:
          root: inputs.cve_id
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1160,
          "y": 960
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '7':
    id: '7'
    taskid: 4d4c7479-f69e-4d8d-8e9e-d24913c46a48
    type: regular
    task:
      id: 4d4c7479-f69e-4d8d-8e9e-d24913c46a48
      version: -1
      name: Get CVE information from XFE
      description: Search for details about the given CVE.
      script: 'XFE_v2|||cve-search'
      type: regular
      iscommand: true
      brand: "XFE_v2"
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      cve_id:
        complex:
          root: inputs.cve_id
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 1720,
          "y": 960
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 81a2e52a-0a2a-4791-8a55-e4249923b7b3
    type: title
    task:
      id: 81a2e52a-0a2a-4791-8a55-e4249923b7b3
      version: -1
      name: CVE enrichment
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '13'
      - '14'
      - '26'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 970,
          "y": 510
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    continueonerrortype: ""
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: fa071711-fc63-4650-86e8-1928ca83bc8c
    type: regular
    task:
      id: fa071711-fc63-4650-86e8-1928ca83bc8c
      version: -1
      name: VulnDB - Get vulnerability details by CVE
      description: Returns full details about vulnerabilities, by CVE ID.
      script: VulnDB|||vulndb-get-vuln-by-cve-id
      type: regular
      iscommand: true
      brand: VulnDB
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      cve_id:
        complex:
          root: inputs.cve_id
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 590,
          "y": 960
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerror: true
    continueonerrortype: ""
    skipunavailable: true
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '13':
    id: '13'
    taskid: 2c6008cc-e42b-4976-86c8-92123558d6b6
    type: title
    task:
      id: 2c6008cc-e42b-4976-86c8-92123558d6b6
      version: -1
      name: VulnDB
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '27'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 400,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '14':
    id: '14'
    taskid: 18b9102f-d968-40d5-8cc3-0e4a1c634e2e
    type: title
    task:
      id: 18b9102f-d968-40d5-8cc3-0e4a1c634e2e
      version: -1
      name: CIRCL CVE Search
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '5'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 970,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '26':
    id: '26'
    taskid: 85a2fa30-ef67-4272-8867-18116129def3
    type: title
    task:
      id: 85a2fa30-ef67-4272-8867-18116129def3
      version: -1
      name: IBM X-Force Exchange
      type: title
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '4'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1530,
          "y": 650
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  '27':
    id: '27'
    taskid: e55035e4-334c-404d-8d69-6e861966f1cb
    type: condition
    task:
      id: e55035e4-334c-404d-8d69-6e861966f1cb
      version: -1
      name: Is VulnDB integration enabled?
      description: Verify that there's a valid instance of "VulnDB" enabled.
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      '#default#':
      - '2'
      'yes':
      - '12'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: VulnDB
                    ignorecase: true
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                    ignorecase: true
                accessor: brand
            iscontext: true
          right:
            value: {}
    view: |-
      {
        "position": {
          "x": 400,
          "y": 790
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    continueonerrortype: ""
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "1_11_yes": 0.52,
      "1_2_#default#": 0.25,
      "27_2_#default#": 0.39,
      "4_2_#default#": 0.1,
      "4_7_yes": 0.46,
      "5_2_#default#": 0.15
    },
    "paper": {
      "dimensions": {
        "height": 995,
        "width": 1937.5,
        "x": 162.5,
        "y": 200
      }
    }
  }
inputs:
- key: cve_id
  value:
    complex:
      root: CVE
      accessor: ID
  required: false
  description: The CVE ID to enrich.
  playbookInputQuery:
outputs:
- contextPath: CVE
  description: The CVE object
  type: string
- contextPath: CVE.ID
  description: The ID of the CVE
  type: string
- contextPath: CVE.CVSS
  description: The CVSS score of the CVE
  type: number
- contextPath: CVE.Published
  description: The date this was published
  type: date
- contextPath: CVE.Modified
  description: When CVE was last modified
  type: date
- contextPath: CVE.Description
  description: The CVE description
  type: string
- contextPath: DBotScore.Vendor
  description: The vendor used to calculate the score.
  type: string
- contextPath: DBotScore.Score
  description: The actual score.
  type: string
- contextPath: DBotScore.Type
  description: The indicator type.
  type: string
- contextPath: DBotScore.Indicator
  description: The indicator that was tested.
  type: string
- contextPath: XFE.CVE.Xfdbid
  description: The XFBID of the CVE.
  type: string
- contextPath: XFE.CVE.RiskLevel
  description: The risk level of the CVE.
  type: string
- contextPath: XFE.CVE.Reported
  description: The reported date of the CVE.
  type: string
- contextPath: XFE.CVE.Cvss
  description: The CVSS information of the CVE.
  type: string
- contextPath: XFE.CVE.Stdcode
  description: The CVE stdcodes.
  type: string
- contextPath: XFE.CVE.Title
  description: The title of the CVE.
  type: string
- contextPath: XFE.CVE.Description
  description: The description of the CVE.
  type: string
- contextPath: XFE.CVE.PlatformsAffected
  description: The affetcted platforms due to the CVE.
  type: string
- contextPath: XFE.CVE.Exploitability
  description: The exploitability of the CVE.
  type: string
- contextPath: VulnDB.Vulnerability
  description: The Vulnerability object
  type: string
- contextPath: VulnDB.Vulnerability.ID
  description: Vulnerability ID.
  type: string
- contextPath: VulnDB.Vulnerability.Title
  description: Vulnerability title (human readable).
  type: string
- contextPath: VulnDB.Vulnerability.Keywords
  description: Vulnerability keywords.
  type: string
- contextPath: VulnDB.Vulnerability.Solution
  description: Vulnerability solution (human readable).
  type: string
- contextPath: VulnDB.Vulnerability.PublishedDate
  description: Vulnerability published date.
  type: date
- contextPath: VulnDB.Vulnerability.TDescription
  description: Vulnerability description (human readable).
  type: string
- contextPath: VulnDB.Vulnerability.SolutionDate
  description: Vulnerability solution date.
  type: date
- contextPath: VulnDB.Vulnerability.DiscoveryDate
  description: Vulnerability discovery date.
  type: date
- contextPath: VulnDB.Vulnerability.ExploitPublishDate
  description: Exploit publish date.
  type: date
- contextPath: VulnDB.CVE-ExtReferences
  description: The Vulnerability References Objects
  type: string
- contextPath: VulnDB.CVE-ExtReferences.Value
  description: CVE (constant string).
  type: string
- contextPath: VulnDB.CvssMetrics
  description: The Common Vulnerability Scoring Metrics
  type: string
- contextPath: VulnDB.CvssMetrics.Id
  description: CVSS reference value.
  type: string
- contextPath: VulnDB.CvssMetrics.AccessVector
  description: CVSS access vector.
  type: string
- contextPath: VulnDB.CvssMetrics.AccessComplexity
  description: CVSS access complexity.
  type: string
- contextPath: VulnDB.CvssMetrics.Authentication
  description: CVSS metric authentication.
  type: string
- contextPath: VulnDB.CvssMetrics.ConfidentialityImpact
  description: CVSS confidentiality impact.
  type: string
- contextPath: VulnDB.CvssMetrics.AvailabilityImpact
  description: CVSS availability impact.
  type: string
- contextPath: VulnDB.CvssMetrics.Generated_on
  description: CVSS metric date.
  type: date
- contextPath: VulnDB.CvssMetrics.Score
  description: CVSS score.
  type: string
- contextPath: VulnDB.cvssMetrics.integrity_impact
  description: CVSS integrity impact.
  type: string
- contextPath: VulnDB.Vendors
  description: Vendors Object
  type: string
- contextPath: VulnDB.Vendors.Id
  description: Vendor ID.
  type: string
- contextPath: VulnDB.Vendor
  description: Vendor Objects
  type: string
- contextPath: VulnDB.Vendor.Name
  description: Vendor name.
  type: string
- contextPath: VulnDB.Products
  description: Products Object
  type: string
- contextPath: VulnDB.Products.Id
  description: Product IDs.
  type: string
- contextPath: VulnDB.Products.Name
  description: Product names.
  type: string
- contextPath: VulnDB.Products.Versions
  description: Products version
  type: string
- contextPath: VulnDB.Products.Versions.Id
  description: Product version IDs.
  type: string
- contextPath: VulnDB.Products.Versions.Name
  description: Product version names.
  type: string
- contextPath: VulnDB.Classification
  description: Classification Object
  type: string
- contextPath: VulnDB.Classification.Longname
  description: Classification name (long).
  type: string
- contextPath: VulnDB.Classification.Description
  description: Classification description (human readable).
  type: string
tests:
- No test
marketplaces:
  - xsoar
  - marketplacev2
contentitemexportablefields:
  contentitemfields: {}
