id: Add Note - Vectra XDR
version: -1
name: Add Note - Vectra XDR
description: This playbook will add a note in Vectra for an entity based on its type.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: dbdf6bf2-a523-4a82-8358-839483e5a73f
    type: start
    task:
      id: dbdf6bf2-a523-4a82-8358-839483e5a73f
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 4c26d7d2-378f-471a-803b-c19be701c292
    type: condition
    task:
      id: 4c26d7d2-378f-471a-803b-c19be701c292
      version: -1
      name: Is entity Account or Host?
      description: Check if the entity is a host or account.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      Account:
      - "2"
      Host:
      - "3"
    separatecontext: false
    conditions:
    - label: Host
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: incident.vectraxdrentitytype
                transformers:
                - operator: toLowerCase
            iscontext: true
          right:
            value:
              simple: host
    - label: Account
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: incident.vectraxdrentitytype
                transformers:
                - operator: toLowerCase
            iscontext: true
          right:
            value:
              simple: account
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 38c10c1d-d0da-4011-8c66-ae79720b405a
    type: regular
    task:
      id: 38c10c1d-d0da-4011-8c66-ae79720b405a
      version: -1
      name: Add note for an Account.
      description: Add a note to an Account.
      script: '|||vectra-entity-note-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entity_id:
        complex:
          root: incident.vectraxdrentityid
      entity_type:
        complex:
          root: incident
          accessor: vectraxdrentitytype
          transformers:
          - operator: toLowerCase
      note:
        complex:
          root: incident
          accessor: vectraxdrentityname
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'This entity_name is '
              suffix:
                value:
                  simple: ' and the entity_id is '
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: incident.vectraxdrentityid
                iscontext: true
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: . The entity_type is an account.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: d76d4aff-1052-4413-8cae-ab9c10610292
    type: regular
    task:
      id: d76d4aff-1052-4413-8cae-ab9c10610292
      version: -1
      name: Add a note for a Host.
      description: Add a note to a Host.
      script: '|||vectra-entity-note-add'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      entity_id:
        complex:
          root: incident.vectraxdrentityid
      entity_type:
        complex:
          root: incident
          accessor: vectraxdrentitytype
          transformers:
          - operator: toLowerCase
      note:
        complex:
          root: incident
          accessor: vectraxdrentityname
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: 'This entity_name is '
              suffix:
                value:
                  simple: ' and the entity_id is '
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: incident.vectraxdrentityid
                iscontext: true
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: . The entity_type is a host.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 758139b7-f317-414e-8b48-bb5470aa686f
    type: title
    task:
      id: 758139b7-f317-414e-8b48-bb5470aa686f
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: ca938cec-795a-4157-8210-0645b4c85230
    type: condition
    task:
      id: ca938cec-795a-4157-8210-0645b4c85230
      version: -1
      name: Is VectraXDR Integration Enabled?
      description: Check VectraXDR integration is active.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: VectraXDR
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
                accessor: brand
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 377.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "11_4_#default#": 0.48
    },
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
