id: Process Incident - Vectra XDR
version: -1
name: Process Incident - Vectra XDR
description: This playbook is used to initiate the processing of an incident. This playbook runs when a pending incident is selected for investigation. It will change the state from pending to active and it will list the available users in Vectra and request the user ID to use for assignment. Once the data collection is complete, it will call the Dispatch Incident - Vectra XDR playbook.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 2d0ad8aa-1356-4346-8de9-68dccdc0a40b
    type: start
    task:
      id: 2d0ad8aa-1356-4346-8de9-68dccdc0a40b
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 7dd99534-e4e0-4ed7-8360-477521510324
    type: playbook
    task:
      id: 7dd99534-e4e0-4ed7-8360-477521510324
      version: -1
      name: Add Notes In The Layout - Vectra XDR
      description: This playbook will add notes in the incident layout.
      playbookName: Add Notes In The Layout - Vectra XDR
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: a55d47e8-a738-4dfc-8b8f-0185043d9331
    type: title
    task:
      id: a55d47e8-a738-4dfc-8b8f-0185043d9331
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 01f8fbf9-f13f-4be7-88e5-0514c9d90215
    type: collection
    task:
      id: 01f8fbf9-f13f-4be7-88e5-0514c9d90215
      version: -1
      name: Get UserID from the user.
      description: Get UserID from the user.
      type: collection
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    message:
      to:
      subject:
      body:
      methods: []
      format: ""
      bcc:
      cc:
      timings:
        retriescount: 2
        retriesinterval: 360
        completeafterreplies: 1
        completeafterv2: true
        completeaftersla: false
    form:
      questions:
      - id: "0"
        label: ""
        labelarg:
          simple: 'Enter User ID for Assignment: '
        required: false
        gridcolumns: []
        defaultrows: []
        type: shortText
        options: []
        optionsarg: []
        fieldassociated: ""
        placeholder: ""
        tooltip: ""
        readonly: false
      title: GetUserID
      description: ""
      sender: ""
      expired: false
      totalanswers: 0
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 1511ffa5-a933-4d3d-83fa-9ca51d155300
    type: regular
    task:
      id: 1511ffa5-a933-4d3d-83fa-9ca51d155300
      version: -1
      name: Delete the context of GetUserID
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      key:
        simple: GetUserID
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: bf04f09f-af14-4cc1-8b9d-f35ab8748e00
    type: regular
    task:
      id: bf04f09f-af14-4cc1-8b9d-f35ab8748e00
      version: -1
      name: List Available Users for Assignment
      description: Returns a list of users.
      script: '|||vectra-user-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: bc52c3d3-7766-4139-81d6-dbab1492bfdf
    type: playbook
    task:
      id: bc52c3d3-7766-4139-81d6-dbab1492bfdf
      version: -1
      name: Dispatch Incident - Vectra XDR
      playbookName: Dispatch Incident - Vectra XDR
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      UserID:
        complex:
          root: GetUserID.Answers
          accessor: "0"
          transformers:
          - operator: LastArrayElement
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 0
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: e1c925a2-20d9-4e0c-81dd-74a1c10eae49
    type: playbook
    task:
      id: e1c925a2-20d9-4e0c-81dd-74a1c10eae49
      version: -1
      name: Add Note - Vectra XDR
      playbookName: Add Note - Vectra XDR
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "10"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.8.0
